apiVersion: v1
kind: Template
metadata:
  name: nextcloud
  annotations:
    description: "Nextcloud - A safe home for all your data"
    tags: "fileshare,nextcloud"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "jngrb"
    template.openshift.io/documentation-url: "https://github.com/jngrb/nextcloud-openshift/blob/master/README.md"
    template.openshift.io/support-url: "https://github.com/jngrb/nextcloud-openshift/issues"
parameters:
- name: NEXTCLOUD_HOST
  description: Application URL of Nextcloud (Route/host)
  required: true
- name: JENKINSFILE_REPO
  description: Jenkins source repository
  value: https://github.com/jngrb/nextcloud-openshift.git
- name: GIT_BRANCH
  description: branch in source repository
  value: master
- name: OLD_NEXTCLOUD_IMAGE_TAG
  description: Tag of the Nextcloud Docker Image to deploy
  value: 16-fpm
- name: NEW_NEXTCLOUD_IMAGE_TAG
  description: Tag of the Nextcloud Docker Image to upgrade to (major version can be incremented max by one)
  value: 17-fpm
- name: BUILD_FIXED_IMAGE
  description: Care for the image with fixed permissions as described in section 'Redis Cache for Sessions without root privileges' of README.md
  value: "true"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
    name: image-upgrade-pipeline
  name: image-upgrade-pipeline
  spec:
    source:
      type: Git
      git:
        uri: "${JENKINSFILE_REPO}"
        ref: "${GIT_BRANCH}"
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: upgrade/Jenkinsfile
        env:
          - name: NEXTCLOUD_HOST
            value: "${NEXTCLOUD_HOST}"
          - name: OLD_NEXTCLOUD_IMAGE_TAG
            value: "${OLD_NEXTCLOUD_IMAGE_TAG}"
          - name: NEW_NEXTCLOUD_IMAGE_TAG
            value: "${NEW_NEXTCLOUD_IMAGE_TAG}"
          - name: BUILD_FIXED_IMAGE
            value: "${BUILD_FIXED_IMAGE}"
